name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 또는 master, 원하는 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/python3.11-kernel
          push: true
          tags: 6loki6/python3.11-jupyter-kernel:latest
